# Naive Bayes 실습

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

In [35]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve
import statsmodels.api as sm

In [9]:
import pandas as pd

In [68]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [17]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [18]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [51]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data,iris.target)
y_pred=fitted.predict(iris.data)

In [52]:
fitted.predict_proba(iris.data)[[1,48,51,100]]
#0,1,2가 될 수 있는 각 확률

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [53]:
fitted.predict(iris.data)[[1,48,51,100]]

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
cfmat=confusion_matrix(iris.target,y_pred)
cfmat

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기(가중치 설정 내가 중요하다고 생각하는 변수)

In [69]:
gnb2=GaussianNB(priors=[1/100,1/100,98/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [50]:
gnb2=GaussianNB(priors=[1/100,98/100,1/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

In [45]:
gnb2=GaussianNB(priors=[98/100,1/100,1/100])
fitted2=gnb2.fit(iris.data,iris.target)
y_pred2=fitted2.predict(iris.data)
confusion_matrix(iris.target,y_pred2)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [64]:
from sklearn.naive_bayes import MultinomialNB

In [56]:
import numpy as np

In [57]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [58]:
X

array([[4, 4, 4, 1, 2, 3, 4, 3, 1, 3, 3, 3, 3, 3, 0, 1, 0, 4, 3, 0, 2, 0,
        4, 0, 1, 3, 1, 4, 1, 4, 2, 1, 2, 2, 0, 3, 3, 0, 3, 0, 1, 4, 1, 2,
        4, 1, 2, 3, 4, 1, 1, 4, 0, 2, 2, 2, 2, 1, 1, 2, 0, 4, 0, 3, 4, 3,
        3, 1, 1, 4, 1, 4, 1, 3, 0, 1, 0, 0, 0, 4, 3, 1, 2, 2, 2, 1, 2, 3,
        2, 1, 3, 2, 3, 1, 0, 0, 1, 1, 4, 2],
       [2, 0, 3, 1, 2, 1, 4, 1, 3, 3, 0, 0, 3, 4, 2, 1, 0, 3, 3, 2, 2, 4,
        4, 0, 1, 3, 4, 3, 0, 4, 1, 4, 0, 4, 2, 2, 4, 1, 0, 2, 4, 4, 0, 4,
        0, 3, 2, 0, 1, 2, 2, 1, 4, 0, 1, 1, 1, 4, 3, 1, 1, 2, 3, 1, 4, 2,
        1, 2, 1, 3, 1, 0, 0, 1, 4, 2, 1, 4, 1, 3, 4, 4, 0, 1, 1, 3, 3, 3,
        4, 3, 4, 2, 4, 2, 1, 4, 0, 3, 3, 4],
       [3, 4, 4, 1, 0, 3, 2, 3, 3, 3, 4, 2, 4, 4, 2, 1, 0, 4, 4, 4, 1, 0,
        1, 4, 4, 3, 0, 1, 3, 2, 1, 4, 4, 1, 4, 1, 1, 2, 1, 4, 4, 4, 2, 2,
        0, 2, 3, 2, 0, 0, 3, 3, 2, 3, 2, 0, 1, 2, 3, 2, 3, 0, 0, 4, 1, 4,
        1, 1, 3, 0, 0, 3, 2, 2, 1, 4, 4, 0, 1, 0, 4, 1, 1, 3, 3, 0, 2, 0,
        0, 3, 3, 2, 3,

In [59]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [62]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB()

In [66]:
print(clf.predict(X))

[1 2 3 4 5 6]


In [67]:
clf.predict_proba(X)

array([[1.00000000e+00, 6.15459414e-31, 4.02313778e-31, 9.06083726e-31,
        5.08154883e-36, 7.94071482e-26],
       [2.94754284e-32, 1.00000000e+00, 1.65209007e-35, 1.53007682e-34,
        1.28542613e-34, 2.82998136e-42],
       [4.89581616e-32, 1.01003478e-34, 1.00000000e+00, 4.36147904e-35,
        4.28045271e-27, 2.71387115e-24],
       [6.22269447e-34, 3.57864073e-37, 2.82030421e-34, 1.00000000e+00,
        5.59832654e-36, 1.50535373e-31],
       [4.96136406e-38, 1.64626792e-37, 6.56653694e-27, 1.77581129e-36,
        1.00000000e+00, 7.94428864e-31],
       [4.37183796e-26, 3.32808044e-40, 1.67578630e-23, 9.25514305e-31,
        1.28198291e-27, 1.00000000e+00]])

- prior 변경해보기

In [76]:
clf2=MultinomialNB(class_prior=[0.1,0.5,0.1,0.1,0.1,0.1])
clf2.fit(X,y)

MultinomialNB(class_prior=[0.1, 0.5, 0.1, 0.1, 0.1, 0.1])

In [78]:
clf2.predict_proba(X)#weiht를 많이 준 확률이 상승한 것을 확인 가능함 적게 준 확률은 감소함

array([[1.00000000e+00, 3.07729707e-30, 4.02313778e-31, 9.06083726e-31,
        5.08154883e-36, 7.94071482e-26],
       [5.89508568e-33, 1.00000000e+00, 3.30418015e-36, 3.06015363e-35,
        2.57085227e-35, 5.65996271e-43],
       [4.89581616e-32, 5.05017392e-34, 1.00000000e+00, 4.36147904e-35,
        4.28045271e-27, 2.71387115e-24],
       [6.22269447e-34, 1.78932036e-36, 2.82030421e-34, 1.00000000e+00,
        5.59832654e-36, 1.50535373e-31],
       [4.96136406e-38, 8.23133961e-37, 6.56653694e-27, 1.77581129e-36,
        1.00000000e+00, 7.94428864e-31],
       [4.37183796e-26, 1.66404022e-39, 1.67578630e-23, 9.25514305e-31,
        1.28198291e-27, 1.00000000e+00]])